name: Android Build

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Run Build
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew assembleDebug
      - name: Store generated APK file
        uses: actions/upload-artifact@v1
        with:
          name: MiraiAndroid
          path: ./app/build/outputs/apk/debug/app-debug.apk
